org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = true
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = true
parchment_minecraft_version = 1.21.1
parchment_mappings_version = 2024.11.17

minecraft_version = 1.21.1
minecraft_version_range = [1.21.1]

neo_version = 21.1.209
neo_version_range = [21.1.207,)
loader_version_range = [4,)

jei_version = 15.20.0.106

mod_id = tome_of_wonders
mod_name = Tome of Wonders
mod_license = https://github.com/platypushasnohat/TomeOfWonders/blob/main/LICENSE
mod_version = 2.0.0
mod_group_id = com.platypushasnohat.tome_of_wonders
mod_authors = .magmastrider., -Ghoul-, platypushasnohat
mod_description = Wonderful things!
